In [1]:
import pandas as pd
import csv

In [2]:
# Define the file path
file_path = './Gestion Stock V4 - Stock Complet.csv'

# Initialize an empty list to store the relevant data
data = []

# Open the CSV file and read the data
with open(file_path, mode='r', encoding='utf-8') as file:
    reader = csv.reader(file)

    # Skip the first 4 lines
    for _ in range(4):
        next(reader)
    
    # Read the header (5th line)
    header = next(reader)[5:12]
    
    # Read the relevant data from column 6 to 12
    for row in reader:
        relevant_data = row[5:12]
        data.append(relevant_data)

# Create a pandas DataFrame from the extracted data
df = pd.DataFrame(data, columns=header)

# Display the DataFrame
df

,EUROCODE,TYPE,DÉSIGNATION,FRS,QTÉ Act,PRIX\nBRUT,PRIX ACHAT
0,8308AGN,PARE BRISE,PB VT TOYOTA HI-LUX 97-05,VSF Centre,0,"83,77","63,67"
1,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,VSF Centre,0,"119,00","90,44"
2,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,VSF Centre,0,,"90,44"
3,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,VSF Centre,0,"89,00","67,64"
4,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,VSF Centre,0,"89,00","67,64"
...,...,...,...,...,...,...,...
10061,4455BGNHI,LUNETTES,LUN VT KIA PICANTO 3 17-,VSF Centre,1,"170,09","136,07"
10062,5172AGN,PARE BRISE,PB VT BT 50 PICK UP/RANGER 07-12,VSF Centre,1,"126,22","100,98"
10063,2482AGACMVZ,PARE BRISE,PB VT AC BMW X1 F48 CAPT CAM 15-22,VSF Centre,1,"237,01","189,61"
10064,4445ASMHT,JOINTS,JC SUP PB KIA SOUL II 14-19,VSF Centre,1,"13,17","10,54"
10065,6244ASRH,JOINTS,JT PB OPEL ASCONA C A ENJ. 81-88,PANTHER PRO,1,"40,12","32,10"

In [3]:
print(df['TYPE'].unique())

['PARE BRISE' 'JOINTS' 'LUNETTES' 'GLACES LATERALES' 'TOIT' 'FEU' 'AUTRES'
 'VITRE PAVILLON' 'RETROVISEUR' 'LEVE-VITRE' 'MECANISME LV' 'ENJOLIVEURS'
 'CACHE RETRO INT' 'RETROVISEUR INT' 'CAMERA' 'OPTIQUE' 'PHARES' 'TOIT '
 'PaRE BRISE' 'LEVE VITRE' 'FAISCEAU' 'TOIT PANO' 'BAIE DE PARE BRISE'
 'jOINTS' 'PHARE' '' 'PARE-BRISE' 'JOINTS ' 'LUNETTES ' 'PARE BRISE '
 'CACHE RETRO' 'MECANISME' 'TOIT PANORAMIQUE' 'OPTIQUES' 'ANTIBROUILLARD'
 'PHARES ']

In [4]:
# Cleaning of the Types
def replace_Type(old_value, new_value):
    df['TYPE'] = df['TYPE'].replace(old_value, new_value)

# Fix Typos and inconsistencies
replace_Type('PaRE BRISE', 'PARE BRISE')
replace_Type('PARE-BRISE', 'PARE BRISE')
replace_Type('PARE BRISE ', 'PARE BRISE')
replace_Type('JOINTS ', 'JOINTS')
replace_Type('jOINTS', 'JOINTS')
replace_Type('ENJOLIVEURS', 'JOINTS')
replace_Type('LUNETTES ', 'LUNETTES')
replace_Type('TOIT', 'TOIT PANORAMIQUE')
replace_Type('TOIT ', 'TOIT PANORAMIQUE')
replace_Type('TOIT PANO', 'TOIT PANORAMIQUE')
replace_Type('VITRE PAVILLON', 'TOIT PANORAMIQUE')
replace_Type('RETROVISEUR', 'RETROVISEUR EXT')
replace_Type('LEVE VITRE', 'LEVE-VITRE')
replace_Type('LEVE-VITRE ', 'LEVE-VITRE')
replace_Type('MECANISME LV', 'LEVE-VITRE')
replace_Type('MECANISME', 'LEVE-VITRE')
replace_Type('OPTIQUES', 'OPTIQUE')
replace_Type('FAISCEAU', 'OPTIQUE')
replace_Type('ANTIBROUILLARD', 'OPTIQUE')
replace_Type('FEU', 'OPTIQUE')
replace_Type('PHARES ', 'OPTIQUE')
replace_Type('PHARES', 'OPTIQUE')
replace_Type('PHARE', 'OPTIQUE')
replace_Type('','AUTRES')
replace_Type('CACHE RETRO INT','CACHE RETRO')
replace_Type('CACHE RETRO','AUTRES')
replace_Type('CAMERA','AUTRES')
replace_Type('BAIE DE PARE BRISE','AUTRES')
types = df['TYPE'].unique()
types

array(['PARE BRISE', 'JOINTS', 'LUNETTES', 'GLACES LATERALES',
       'TOIT PANORAMIQUE', 'OPTIQUE', 'AUTRES', 'RETROVISEUR EXT',
       'LEVE-VITRE', 'RETROVISEUR INT'], dtype=object)

In [5]:
import os, sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from agent import agent

Logged in https://rpbm-pre-prod-18872472.dev.odoo.com/ as admin

In [6]:
AutoNickelCategories = {
    "Pare-Brise": ["PARE BRISE"],
    "Lunettes": ["LUNETTES"],
    "Glace latérale": ["GLACES LATERALES", "Custode", "Déflecteur"],
    "Joints": ["JOINTS"],
    "Consommables": [],
    "Films solaires": [],
    "Autres": [
        "TOIT PANORAMIQUE",
        "RETROVISEUR EXT",
        "RETROVISEUR INT",
        "LEVE-VITRE",
        "OPTIQUE",
        "AUTRES",
    ],
    "Services": [],
    "Accessoires": [],
}
for k,values in AutoNickelCategories.items():
    for value in values:
        if value not in types:
            print(f"{value} not found in the types")

Custode not found in the types
Déflecteur not found in the types

In [7]:
class Category:
    def __init__(self, name:str, id:int, parent_id:int):
        self.name = name
        self.id = id
        self.parent_id = parent_id

    def __str__(self):
        return self.__dict__
        
categoriesData = agent.search_read('product.category', [], ['name', 'id', 'parent_id'])
categories = [Category(**category) for category in categoriesData]

In [8]:
for categorie in categories:
    print(categorie.__dict__)

{'name': 'All', 'id': 1, 'parent_id': False}
{'name': 'Deliveries', 'id': 6, 'parent_id': [1, 'All']}
{'name': 'Expenses', 'id': 3, 'parent_id': [1, 'All']}
{'name': 'Saleable', 'id': 2, 'parent_id': [1, 'All']}
{'name': 'Accessoires', 'id': 7, 'parent_id': [2, 'All / Saleable']}
{'name': 'Essuie-Glace', 'id': 8, 'parent_id': [7, 'All / Saleable / Accessoires']}
{'name': 'Booking Fees', 'id': 14, 'parent_id': [2, 'All / Saleable']}
{'name': 'Consommables Atelier', 'id': 10, 'parent_id': [2, 'All / Saleable']}
{'name': 'Events', 'id': 5, 'parent_id': [2, 'All / Saleable']}
{'name': "Main d'Oeuvre", 'id': 13, 'parent_id': [2, 'All / Saleable']}
{'name': 'Outillages', 'id': 9, 'parent_id': [2, 'All / Saleable']}
{'name': 'Pièces de Rechange', 'id': 11, 'parent_id': [2, 'All / Saleable']}
{'name': 'PoS', 'id': 4, 'parent_id': [2, 'All / Saleable']}

In [9]:
SaleableCategory = next(categorie for categorie in categories if categorie.name == 'Saleable')
SaleableCategory.__dict__

{'name': 'Saleable', 'id': 2, 'parent_id': [1, 'All']}

In [10]:
def ensureCategory(name, parent_id):
    # Search for the category in categories
    category = next((c for c in categories if c.name == name), None)
    # If the category does not exist, create it
    if category is None:
        category_id = agent.create('product.category', {'name': name, 'parent_id': parent_id})
        # Update the categories 
        category = agent.search_read('product.category', [('id', '=', category_id)], ['name', 'id', 'parent_id'])[0]
        category = Category(**category)
        categories.append(category)
    return category

for k,values in AutoNickelCategories.items():
    if len(values) == 0:
        continue
    if len(values) == 1:
        # Si il n'y a qu'une seule valeur, on crée directement la catégorie enfant
        k = values[0]
        category = ensureCategory(k, SaleableCategory.id)
    else:
        # Si il y a plusieurs valeurs, on crée la catégorie parente et les catégories enfants
        category = ensureCategory(k, SaleableCategory.id)    
        for child_categories in values:
            ensureCategory(child_categories, category.id)

for categorie in categories:
    print(categorie.__dict__)

{'name': 'All', 'id': 1, 'parent_id': False}
{'name': 'Deliveries', 'id': 6, 'parent_id': [1, 'All']}
{'name': 'Expenses', 'id': 3, 'parent_id': [1, 'All']}
{'name': 'Saleable', 'id': 2, 'parent_id': [1, 'All']}
{'name': 'Accessoires', 'id': 7, 'parent_id': [2, 'All / Saleable']}
{'name': 'Essuie-Glace', 'id': 8, 'parent_id': [7, 'All / Saleable / Accessoires']}
{'name': 'Booking Fees', 'id': 14, 'parent_id': [2, 'All / Saleable']}
{'name': 'Consommables Atelier', 'id': 10, 'parent_id': [2, 'All / Saleable']}
{'name': 'Events', 'id': 5, 'parent_id': [2, 'All / Saleable']}
{'name': "Main d'Oeuvre", 'id': 13, 'parent_id': [2, 'All / Saleable']}
{'name': 'Outillages', 'id': 9, 'parent_id': [2, 'All / Saleable']}
{'name': 'Pièces de Rechange', 'id': 11, 'parent_id': [2, 'All / Saleable']}
{'name': 'PoS', 'id': 4, 'parent_id': [2, 'All / Saleable']}
{'name': 'PARE BRISE', 'id': 15, 'parent_id': [2, 'All / Saleable']}
{'name': 'LUNETTES', 'id': 16, 'parent_id': [2, 'All / Saleable']}
{'name': 'Glace latérale', 'id': 17, 'parent_id': [2, 'All / Saleable']}
{'name': 'GLACES LATERALES', 'id': 18, 'parent_id': [17, 'All / Saleable / Glace latérale']}
{'name': 'Custode', 'id': 19, 'parent_id': [17, 'All / Saleable / Glace latérale']}
{'name': 'Déflecteur', 'id': 20, 'parent_id': [17, 'All / Saleable / Glace latérale']}
{'name': 'JOINTS', 'id': 21, 'parent_id': [2, 'All / Saleable']}
{'name': 'Autres', 'id': 22, 'parent_id': [2, 'All / Saleable']}
{'name': 'TOIT PANORAMIQUE', 'id': 23, 'parent_id': [22, 'All / Saleable / Autres']}
{'name': 'RETROVISEUR EXT', 'id': 24, 'parent_id': [22, 'All / Saleable / Autres']}
{'name': 'RETROVISEUR INT', 'id': 25, 'parent_id': [22, 'All / Saleable / Autres']}
{'name': 'LEVE-VITRE', 'id': 26, 'parent_id': [22, 'All / Saleable / Autres']}
{'name': 'OPTIQUE', 'id': 27, 'parent_id': [22, 'All / Saleable / Autres']}
{'name': 'AUTRES', 'id': 28, 'parent_id': [22, 'All / Saleable / Autres']}

In [11]:
# Pour chaque category dans la liste des categories on attribue l'id dans le dataFrame
df['categ_id'] = SaleableCategory.id
def assignCategory(categorie:Category):
    name = categorie.name
    if name in df['TYPE'].unique():
        df.loc[df['TYPE'] == categorie.name, 'categ_id'] = categorie.id

for categorie in categories:
    assignCategory(categorie)
df['categ_id'].unique()

array([15, 21, 16, 18, 23, 27, 28, 24, 26, 25])

In [12]:
df[df['categ_id'] == 2]

Empty DataFrame
Columns: [EUROCODE, TYPE, DÉSIGNATION, FRS, QTÉ Act, PRIX
BRUT, PRIX ACHAT, categ_id]
Index: []

In [13]:
# Pour les sans Désignation on attribue l'EUROCODE
df.loc[(df['DÉSIGNATION'] == '') | (df['DÉSIGNATION'] == False), 'DÉSIGNATION'] = df['EUROCODE']

In [14]:
# Keep only the rows where EUROCODE is not null and defined
nullDf = df[(df['EUROCODE']=='' ) | (df['EUROCODE']=='0') | (df['EUROCODE'] == False)]
df = df.drop(nullDf.index)

In [15]:
# Create a subset of the DataFrame with only the relevant columns and unique EUROCODE
df = df[['EUROCODE', 'TYPE', 'DÉSIGNATION', 'PRIX\nBRUT', 'PRIX ACHAT', 'categ_id']]
df = df.drop_duplicates(subset='EUROCODE')
df

,EUROCODE,TYPE,DÉSIGNATION,PRIX\nBRUT,PRIX ACHAT,categ_id
0,8308AGN,PARE BRISE,PB VT TOYOTA HI-LUX 97-05,"83,77","63,67",15
1,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,"119,00","90,44",15
3,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,"89,00","67,64",15
7,3359AGS,PARE BRISE,PB VT FIAT PANDA II 03-12,"89,00","67,64",15
9,7248AGS1B,PARE BRISE,PB VT RENAULT CLIO II 98-05,"48,87","37,14",15
...,...,...,...,...,...,...
10052,6244ABZBZ,PARE BRISE,PB BZBZ ASCONA C SS EMBASE 81-88,"88,11","70,49",15
10053,6520LGNH3RQO,GLACES LATERALES,CUST OUVR ARG VT 106 3P 91-03,"48,30","38,64",18
10055,7279BGSSA,LUNETTES,LUN VT RENAULT FLUENCE 4P ANT 10-15,"144,18","115,34",16
10057,4004LGSH5FQ,GLACES LATERALES,DEFL AVG VT HONDA JAZZ 09-15,"119,04","95,23",18
10065,6244ASRH,JOINTS,JT PB OPEL ASCONA C A ENJ. 81-88,"40,12","32,10",21

In [16]:
# Rename columns
df = df.rename(columns={'EUROCODE': 'default_code', 'TYPE': 'description_picking', 'DÉSIGNATION': 'name', 'PRIX\nBRUT': 'list_price', 'PRIX ACHAT': 'standard_price'})
df

,default_code,description_picking,name,list_price,standard_price,categ_id
0,8308AGN,PARE BRISE,PB VT TOYOTA HI-LUX 97-05,"83,77","63,67",15
1,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,"119,00","90,44",15
3,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,"89,00","67,64",15
7,3359AGS,PARE BRISE,PB VT FIAT PANDA II 03-12,"89,00","67,64",15
9,7248AGS1B,PARE BRISE,PB VT RENAULT CLIO II 98-05,"48,87","37,14",15
...,...,...,...,...,...,...
10052,6244ABZBZ,PARE BRISE,PB BZBZ ASCONA C SS EMBASE 81-88,"88,11","70,49",15
10053,6520LGNH3RQO,GLACES LATERALES,CUST OUVR ARG VT 106 3P 91-03,"48,30","38,64",18
10055,7279BGSSA,LUNETTES,LUN VT RENAULT FLUENCE 4P ANT 10-15,"144,18","115,34",16
10057,4004LGSH5FQ,GLACES LATERALES,DEFL AVG VT HONDA JAZZ 09-15,"119,04","95,23",18
10065,6244ASRH,JOINTS,JT PB OPEL ASCONA C A ENJ. 81-88,"40,12","32,10",21

In [17]:
# Set list_price and standard_price to numeric if possible, else set to 0
# df['list_price'] = pd.to_numeric(df['list_price'].replace({',': '.'}, regex=True, inplace=True))
# df['standard_price'] = pd.to_numeric(df['standard_price'].replace({',': '.'}, regex=True, inplace=True))
df['list_price'].replace({',': '.'}, regex=True, inplace=True)
df['standard_price'].replace({',': '.'}, regex=True, inplace=True)
# if a value is not numeric, it will be set to NaN then to 0
df['list_price'] = pd.to_numeric(df['list_price'], errors='coerce').fillna(0)
df['standard_price'] = pd.to_numeric(df['standard_price'], errors='coerce').fillna(0)
# Change the data type of list_price and standard_price to float

df

C:\Users\stan\AppData\Local\Temp\ipykernel_7296\1878025348.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['list_price'].replace({',': '.'}, regex=True, inplace=True)
C:\Users\stan\AppData\Local\Temp\ipykernel_7296\1878025348.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['standard_price'].replace({',': '.'}, regex=True, inplace=True)

,default_code,description_picking,name,list_price,standard_price,categ_id
0,8308AGN,PARE BRISE,PB VT TOYOTA HI-LUX 97-05,83.77,63.67,15
1,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,119.00,90.44,15
3,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,89.00,67.64,15
7,3359AGS,PARE BRISE,PB VT FIAT PANDA II 03-12,89.00,67.64,15
9,7248AGS1B,PARE BRISE,PB VT RENAULT CLIO II 98-05,48.87,37.14,15
...,...,...,...,...,...,...
10052,6244ABZBZ,PARE BRISE,PB BZBZ ASCONA C SS EMBASE 81-88,88.11,70.49,15
10053,6520LGNH3RQO,GLACES LATERALES,CUST OUVR ARG VT 106 3P 91-03,48.30,38.64,18
10055,7279BGSSA,LUNETTES,LUN VT RENAULT FLUENCE 4P ANT 10-15,144.18,115.34,16
10057,4004LGSH5FQ,GLACES LATERALES,DEFL AVG VT HONDA JAZZ 09-15,119.04,95.23,18
10065,6244ASRH,JOINTS,JT PB OPEL ASCONA C A ENJ. 81-88,40.12,32.10,21

In [18]:
# Add column type as 'product'
df['type'] = 'product'
df

,default_code,description_picking,name,list_price,standard_price,categ_id,type
0,8308AGN,PARE BRISE,PB VT TOYOTA HI-LUX 97-05,83.77,63.67,15,product
1,6570AGNMVZ,PARE BRISE,PB VT PEUGEOT 308 II+ CAPT 13-,119.00,90.44,15,product
3,6549AGS,PARE BRISE,PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14,89.00,67.64,15,product
7,3359AGS,PARE BRISE,PB VT FIAT PANDA II 03-12,89.00,67.64,15,product
9,7248AGS1B,PARE BRISE,PB VT RENAULT CLIO II 98-05,48.87,37.14,15,product
...,...,...,...,...,...,...,...
10052,6244ABZBZ,PARE BRISE,PB BZBZ ASCONA C SS EMBASE 81-88,88.11,70.49,15,product
10053,6520LGNH3RQO,GLACES LATERALES,CUST OUVR ARG VT 106 3P 91-03,48.30,38.64,18,product
10055,7279BGSSA,LUNETTES,LUN VT RENAULT FLUENCE 4P ANT 10-15,144.18,115.34,16,product
10057,4004LGSH5FQ,GLACES LATERALES,DEFL AVG VT HONDA JAZZ 09-15,119.04,95.23,18,product
10065,6244ASRH,JOINTS,JT PB OPEL ASCONA C A ENJ. 81-88,40.12,32.10,21,product

In [19]:
data = df.to_dict(orient='records')
data

[{'default_code': '8308AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT TOYOTA HI-LUX 97-05',
  'list_price': 83.77,
  'standard_price': 63.67,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6570AGNMVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 308 II+ CAPT 13-',
  'list_price': 119.0,
  'standard_price': 90.44,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6549AGS',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUG.107 / CITR.C1/ TOY.AYGO 05-14',
  'list_price': 89.0,
  'standard_price': 67.64,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3359AGS',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT FIAT PANDA II 03-12',
  'list_price': 89.0,
  'standard_price': 67.64,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7248AGS1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT CLIO II 98-05',
  'list_price': 48.87,
  'standard_price': 37.14,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7246AGS6Z',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT KANGOO 98-07',
  'list_price': 51.16,
  'standard_price': 38.88,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2726AGSV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT CITROEN C3 3/5P 02-09',
  'list_price': 79.9,
  'standard_price': 60.72,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2448AGNMV1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BMW SIE 1E87 BNE/CAB+CAP.04-11',
  'list_price': 131.0,
  'standard_price': 99.56,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7293AGSMV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT CAPTUR+CAPT.13-',
  'list_price': 119.0,
  'standard_price': 90.44,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7290AGSMV1M',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT CLIO IV+CAPT. 13-',
  'list_price': 91.0,
  'standard_price': 69.16,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3572AGSVW',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT FORD FIESTA VI 08-12',
  'list_price': 111.0,
  'standard_price': 84.36,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8604AGSGYMVWZ95',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY AUDI A1+CAPT 01/12-',
  'list_price': 129.0,
  'standard_price': 98.04,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8603AGSGYVWZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY VOLKSWAGEN POLO V 10-',
  'list_price': 105.0,
  'standard_price': 79.8,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5351AGSGYMVW',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY W203 +CAP.PL/LUM. BNE/BK 00-03',
  'list_price': 149.4,
  'standard_price': 113.54,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2454AGSGYMV1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY BMW SIE3 COUPE E92+CAPT 06-13',
  'list_price': 149.2,
  'standard_price': 113.39,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8020ALG1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SUZUKI GRAND VITARA 98-05',
  'list_price': 120.0,
  'standard_price': 91.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5158AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT MAZDA B2500/BT 50 PICK UP 98-12',
  'list_price': 129.6,
  'standard_price': 98.5,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7276AGS',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT DACIA SANDERO/DUSTER 08-',
  'list_price': 66.08,
  'standard_price': 50.22,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8558AGNVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT VW GOLF IV/BORA 98-03',
  'list_price': 83.64,
  'standard_price': 63.57,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6520AGN2B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 106 /SAXO 91-03',
  'list_price': 54.26,
  'standard_price': 41.24,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7279AGAMV1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.MEGANE III BNE/BK+CAPT 08-15',
  'list_price': 101.0,
  'standard_price': 76.76,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2460AGSGYMV1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY BMW X1 E84+ CAPT 10-15',
  'list_price': 155.0,
  'standard_price': 117.8,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7610AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SEAT IBIZA 4 / CORDOBA 3 02-08',
  'list_price': 89.0,
  'standard_price': 67.64,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7262AGAMV1R',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACOUS.RENAULT CLIO 3 +CAPT 05-14',
  'list_price': 126.0,
  'standard_price': 95.76,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7268AGSV1M',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT TWINGO II 07-14',
  'list_price': 71.0,
  'standard_price': 53.96,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2732AGSVW',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT CITROEN C4 04-10',
  'list_price': 99.9,
  'standard_price': 75.92,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6542ACDMVZ6P',
  'description_picking': 'PARE BRISE',
  'name': 'PB ATH 307 +CAPT.PL/LU RETR.ELEC 03-07',
  'list_price': 209.0,
  'standard_price': 158.84,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6542AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 307 BNE/SW 01-07',
  'list_price': 129.0,
  'standard_price': 98.04,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2732ACDMVW2P',
  'description_picking': 'PARE BRISE',
  'name': 'PB REFL.C4+CAPT+RETR.ELECT.04-10',
  'list_price': 186.0,
  'standard_price': 141.36,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2740AGAMVZ1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.CITROEN C5 II+ CAPT 08-',
  'list_price': 129.0,
  'standard_price': 98.04,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6337AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT OPEL MOKKA 12-',
  'list_price': 129.0,
  'standard_price': 98.04,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5172AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BT 50 PICK UP/RANGER 07-12',
  'list_price': 99.0,
  'standard_price': 75.24,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7274AGSV1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT KANGOO II +EMB. 07-',
  'list_price': 95.0,
  'standard_price': 72.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6539AGSV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 206/206+ BNE/SW 98-14',
  'list_price': 67.24,
  'standard_price': 51.1,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7262AGSV1M',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT CLIO 3 05-14',
  'list_price': 69.0,
  'standard_price': 52.44,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6548AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 207 06-',
  'list_price': 116.1,
  'standard_price': 88.24,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2741AGSVZ1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BERLINGO/PARTNER+EMB 08-',
  'list_price': 93.6,
  'standard_price': 71.14,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5966AGN1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT NISS.NAVARA D22/NP300 98-',
  'list_price': 116.0,
  'standard_price': 88.16,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6564AGNVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT PEUGEOT 208/2008 3/5P. 11-',
  'list_price': 119.0,
  'standard_price': 90.44,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6554AGAMVW3B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACOUS.308 +CAPT.BNE/SW 07-13',
  'list_price': 153.0,
  'standard_price': 116.28,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '4141AGSV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT HYUNDAI IX35 10-',
  'list_price': 159.0,
  'standard_price': 120.84,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6044AGSMV1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT NISSAN QASHQAI +CAPT 07-14',
  'list_price': 124.0,
  'standard_price': 94.24,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7281AGSV1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT MASTER III / MOVANO +EMB. 09-',
  'list_price': 117.8,
  'standard_price': 89.53,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3741AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT IVECO DAILY II 98-',
  'list_price': 107.8,
  'standard_price': 81.93,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3752AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SCUDO/EXPERT/JUMPY 07-',
  'list_price': 109.0,
  'standard_price': 82.84,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6523AGN1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BOXER 1 /JUMPER 1 94-06',
  'list_price': 86.15,
  'standard_price': 65.47,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7252AGSV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT TRAFIC II EMB 115MM 01-08',
  'list_price': 97.9,
  'standard_price': 74.4,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2724AGS1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BERLINGO / PARTNER 96-08',
  'list_price': 55.49,
  'standard_price': 42.17,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3750AGSVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BOXER/JUMPER2/DUCATO 3 06-14',
  'list_price': 139.0,
  'standard_price': 105.64,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7247AGN2P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT MASTER II / MASCOTT / MO. 99-09',
  'list_price': 77.0,
  'standard_price': 58.52,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5426AGNGN1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTVT SPRINTER PM + EMB CH.CAB. 95-06',
  'list_price': 106.05,
  'standard_price': 80.6,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2735AGAMVZ6A',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT CITROEN C4 PICASSO 1+CAPT 06-',
  'list_price': 389.68,
  'standard_price': 296.16,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2735AGAMVZ6A-T',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT CITROEN C4 PICASSO 1+CAPT 06-',
  'list_price': 389.68,
  'standard_price': 296.16,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2743CGSGYVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTGY CITROEN C3 3/5P ZENITH 09-',
  'list_price': 239.81,
  'standard_price': 182.26,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2753ACDIMVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB ATH.C4 PICASSO II +CAPT. 13-',
  'list_price': 349.0,
  'standard_price': 265.24,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8301ALGGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB LAND CRUISER HDJ90',
  'list_price': 230.94,
  'standard_price': 230.94,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6253AGNBL',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTBL OPEL VECTRA A              88-95',
  'list_price': 78.54,
  'standard_price': 62.83,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2726ACCMV1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB REFL.CITROEN C3 +CAPT           03-09',
  'list_price': 189.0,
  'standard_price': 151.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6548ACCMVZ1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB REFL.PEUGEOT 207+CAPT             06-',
  'list_price': 205.99,
  'standard_price': 164.79,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8600AGAMVZ1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACOUS.VW GOLF VI+CAPT 08-12',
  'list_price': 117.63,
  'standard_price': 94.1,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8600AGAVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACOUST.VW GOLF VI      08-12',
  'list_price': 117.63,
  'standard_price': 94.1,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7300AGAMVZ1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.RENAULT KADJAR +CAPT. 15-',
  'list_price': 189.0,
  'standard_price': 151.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7300AGAVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.RENAULT KADJAR  15-',
  'list_price': 139.0,
  'standard_price': 111.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6312AGSVZ1M',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT OPEL CORSA D                 06-14',
  'list_price': 109.0,
  'standard_price': 87.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2741ACCMVZ2P',
  'description_picking': 'PARE BRISE',
  'name': 'PB ATH BERLINGO/PARTNER+CAPT.08-',
  'list_price': 169.0,
  'standard_price': 135.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '5628ABL',
  'description_picking': 'PARE BRISE',
  'name': 'PB BL MITSUBIHI L 200              87-96',
  'list_price': 124.85,
  'standard_price': 99.88,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3345AGS',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT EVASION/806/ULYS./ZETA       95-07',
  'list_price': 88.0,
  'standard_price': 70.4,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3976AGSV1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT HONDA CIVIC 3P HBK           03-05',
  'list_price': 140.0,
  'standard_price': 112.0,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8394AGAGNMZ1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VTVT LANDCRUISER LHD CAPT. 09-',
  'list_price': 159.0,
  'standard_price': 127.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6564AGAMVZ2B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.PEUG.208/2008 3/5P+CAPT.13-',
  'list_price': 129.0,
  'standard_price': 103.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7619AGAVZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SEAT LEON           13-',
  'list_price': 142.9,
  'standard_price': 114.32,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7619AGAMVZ1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.SEAT LEON +CAPT     13-',
  'list_price': 159.0,
  'standard_price': 127.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6312AGSMVZ1R',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT OPEL CORSA D +CAPT           06-14',
  'list_price': 119.19,
  'standard_price': 95.35,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3366AGSZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT FIAT 500                 07-',
  'list_price': 109.0,
  'standard_price': 87.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3373AGSWZ',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT FIAT 500L      12-',
  'list_price': 109.0,
  'standard_price': 87.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3572AGSMVW1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT FORD FIESTA VI+CAPT      08-12',
  'list_price': 109.0,
  'standard_price': 87.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8010AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SUZUKI / SANTANA VITARA      88-97',
  'list_price': 122.93,
  'standard_price': 98.34,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6069AGAMV1P',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACO.NISSAN JUKE+CAPT.10-14',
  'list_price': 129.0,
  'standard_price': 103.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '6069AGAV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT ACOUS.NISSAN JUKE   10-',
  'list_price': 119.0,
  'standard_price': 95.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8340AGS',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT TOYOTA COROLLA 3/5 P         02-07',
  'list_price': 99.0,
  'standard_price': 79.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8340ASMH',
  'description_picking': 'JOINTS',
  'name': 'JC PB TOYOTA COROLLA 3/5P HB       02-07',
  'list_price': 12.0,
  'standard_price': 9.6,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '6549BGSHO',
  'description_picking': 'LUNETTES',
  'name': 'LUN VT CITROEN C1/PEUGEOT 107   05-14',
  'list_price': 99.0,
  'standard_price': 79.2,
  'categ_id': 16,
  'type': 'product'},
 {'default_code': '3547AGN1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT MAVERICK/TERRANO II          94-',
  'list_price': 107.9,
  'standard_price': 86.32,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3547ASMRT',
  'description_picking': 'JOINTS',
  'name': 'JC SUP.PB MAVERICK/TERRANO II    94-01',
  'list_price': 10.39,
  'standard_price': 8.31,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '2447AGNV',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BMW SERIE 3 E90 BNE/E91BK 05-12',
  'list_price': 95.0,
  'standard_price': 76.0,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '2447ASMSB',
  'description_picking': 'JOINTS',
  'name': 'JC INF.PB BMW SIE3 E90             05-12',
  'list_price': 5.8,
  'standard_price': 4.64,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '2447ASMST',
  'description_picking': 'JOINTS',
  'name': 'JC SUP PB BMW SIE3 E90             05-12',
  'list_price': 9.5,
  'standard_price': 7.6,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '7251AGAVW1R',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT RENAULT ESPACE IV            02-14',
  'list_price': 199.0,
  'standard_price': 159.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7251AKMV',
  'description_picking': 'JOINTS',
  'name': 'JC KIT COMPLET PB RENAULT ESPACE 4 02-14',
  'list_price': 74.93,
  'standard_price': 59.94,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '2447AGNMV1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT BMW SERIE E90 BNE/BK+CAPT  05-12',
  'list_price': 123.0,
  'standard_price': 98.4,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '3014LGSH5FD',
  'description_picking': 'GLACES LATERALES',
  'name': 'DESC.AVG VT DAEWOO KALOS/AVEO 4/5P 02-08',
  'list_price': 59.0,
  'standard_price': 47.2,
  'categ_id': 18,
  'type': 'product'},
 {'default_code': '8032AGN',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SUZUKI GRAND VITARA          05-14',
  'list_price': 142.0,
  'standard_price': 113.6,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '8032ASMR',
  'description_picking': 'JOINTS',
  'name': 'JC PB SUZUKI GRAND VITARA 2    05-14',
  'list_price': 29.0,
  'standard_price': 23.2,
  'categ_id': 21,
  'type': 'product'},
 {'default_code': '7250RGSH5FD',
  'description_picking': 'GLACES LATERALES',
  'name': 'DESC.AVD VT VELSATIS               01-09',
  'list_price': 65.01,
  'standard_price': 52.01,
  'categ_id': 18,
  'type': 'product'},
 {'default_code': '5427AGN1C',
  'description_picking': 'PARE BRISE',
  'name': 'PB VT SPRINTER GM + EMBASE FOURG. 95-06',
  'list_price': 89.0,
  'standard_price': 71.2,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7237ACC1B',
  'description_picking': 'PARE BRISE',
  'name': 'PB REFLECHISSANT LAGUNA I          94-00',
  'list_price': 134.48,
  'standard_price': 107.58,
  'categ_id': 15,
  'type': 'product'},
 {'default_code': '7237AKMHT',
  'description_picking': 'JOINTS',

In [20]:
import sys
import os
print(os.getcwd())
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from agent import agent
agent.create('product.template', data)

d:\git\rpbm\Jobs\Gestion Stock

[181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 ...]